# Pipeline that is triggered on completion of azure-pipelines.yml and azure-pipelines-resource-trigger.yml

trigger: none

resources:
  pipelines:
    - pipeline: MyMainAlias
      source: flcdrg.azure-pipelines-resource-triggers-main
      branch: main
      trigger:
        branches:
          include:
            - main

    - pipeline: MyChildAlias
      source: flcdrg.azure-pipelines-resource-triggers-child
      branch: main
      trigger:
        branches:
          include:
            - main

    - pipeline: ThirdAlias
      source: flcdrg.azure-pipelines-resource-triggers-stage
      branch: main
         
pool:
  vmImage: ubuntu-latest

jobs:
  - deployment: deploy
    displayName: deploy triggered by $(RESOURCES.TRIGGERINGALIAS) ${{ variables['resources.triggeringAlias'] }}
    environment: "Environment1"
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "##vso[build.updatebuildnumber]$(Resources.Pipeline.MyChildAlias.RunName)"
              displayName: "Update build number"
            - script: printenv
              displayName: "Environment from $(RESOURCES.TRIGGERINGALIAS)"
            - script: ls -al $(PIPELINE.WORKSPACE)
              displayName: "List files in the pipeline workspace"
