# Pipeline that is triggered on completion of azure-pipelines.yml and azure-pipelines-resource-trigger.yml

trigger: none

resources:
  pipelines:
    - pipeline: MyMainAlias
      source: flcdrg.azure-pipelines-resource-triggers-main
      branch: main
      trigger:
        branches:
          include:
            - main

    - pipeline: MyChildAlias
      source: flcdrg.azure-pipelines-resource-triggers-child
      branch: main
      trigger:
        branches:
          include:
            - main
pool:
  vmImage: ubuntu-latest

jobs:
  - deployment: deploy
    displayName: deploy triggered by $(RESOURCES.TRIGGERINGALIAS)
    environment: "Environment1"
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "##vso[build.updatebuildnumber]$(Resources.Pipeline.MyChildAlias.RunName)"
            - script: printenv
              displayName: "Run a one-line script"
