# Simple main pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'dotnet: Use .NET SDK 6.x'
  inputs:
    version: 6.x
    packageType: sdk
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: nbgv cloud
  displayName: 'nbgv'

- publish: $(System.DefaultWorkingDirectory)
  artifact: Stuff