# Pipeline that is triggered on completion of azure-pipelines.yml

trigger: none

resources:
  pipelines:
  - pipeline: MyCIAlias
    source: flcdrg.azure-pipelines-resource-triggers-main
    branch: main      ### This branch input cannot have wild cards. It is used for evaluating default version when pipeline is triggered manually or scheduled.
    trigger:
      branches:
        include:
          - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "##vso[build.updatebuildnumber]$(Resources.Pipeline.MyCIAlias.RunName)"
- script: printenv
  displayName: 'Run a one-line script'
