# Pipeline that is triggered on completion of azure-pipelines.yml, when stage 'Stage1' has completed

trigger: none

resources:
  pipelines:
    - pipeline: MyCIAlias
      source: flcdrg.azure-pipelines-resource-triggers-main
      branch: main
      trigger:
        branches:
          include:
            - main
        stages:
          - Stage1
          - Stage2

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo "##vso[build.updatebuildnumber]$(Resources.Pipeline.MyCIAlias.RunName)"

  - script: |
      env -0 | sort -z | tr '\0' '\n'
    displayName: 'Script: Dump environment'

  - publish: $(System.DefaultWorkingDirectory)
    artifact: Stuff
