# Simple main pipeline
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- publish: $(System.DefaultWorkingDirectory)
  artifact: Stuff